# Generated by Django 5.2.1 on 2025-05-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registrationtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationToken',
            new_name='RegistrationLinks',
        ),
    ]
